import type { Metadata } from "next";
import { Geist, Geist_Mono, Klee_One } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const kanjiFont = Klee_One({
  weight: "400",
  subsets: ["japanese"],
  display: "swap",
  variable: "--font-kanji",
});

export const metadata: Metadata = {
  title: "N1 Kanji Practice",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${kanjiFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
